force-app/main/default/objects/OrgLimitType__c/OrgLimitType__c.object-meta.xml
<CustomObject>
    <label>Org Limit Type</label>
    <nameField>
        <displayFormat>OLT-{0000}</displayFormat>
        <label>OrgLimitType Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Org Limit Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrgLimitType__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If the org type is required to be monitored or not.</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrgLimitType__c/fields/LastRetrievalDate__c.field-meta.xml
<CustomField>
    <fullName>LastRetrievalDate__c</fullName>
    <label>Last Retrieval Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/OrgLimitType__c/fields/OrgLimitName__c.field-meta.xml
<CustomField>
    <fullName>OrgLimitName__c</fullName>
    <description>Api Name of the Org Limit key</description>
    <label>Org Limit Name</label>
    <length>126</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/OrgLimitType__c/fields/RetrievalFrequency__c.field-meta.xml
<CustomField>
    <fullName>RetrievalFrequency__c</fullName>
    <description>Number of hours, for which the org limits would be retrieved and stored in snapshot</description>
    <label>Retrieval Frequency (Hours)</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Snapshot__c/Snapshot__c.object-meta.xml
<CustomObject>
    <label>Snapshot</label>
    <nameField>
        <displayFormat>SNAP-{0000}</displayFormat>
        <label>Snapshot Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Snapshots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Snapshot__c/fields/ApexJobName__c.field-meta.xml
<CustomField>
    <fullName>ApexJobName__c</fullName>
    <label>Apex Job Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Snapshot__c/fields/AsyncApexJobId__c.field-meta.xml
<CustomField>
    <fullName>AsyncApexJobId__c</fullName>
    <label>Async Apex Job Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Snapshot__c/fields/IsExpired__c.field-meta.xml
<CustomField>
    <fullName>IsExpired__c</fullName>
    <formula>IF(RecordType.DeveloperName == &apos;Org_Limit_Snapshot&apos;, TODAY() &gt; DATEVALUE(CreatedDate) +  OrgLimitType__r.RetentionPeriod__c, TODAY() &gt; DATEVALUE(CreatedDate) + 3)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Expired</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Snapshot__c/fields/MaxLimit__c.field-meta.xml
<CustomField>
    <fullName>MaxLimit__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Maxium Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Snapshot__c/fields/OrgLimitName__c.field-meta.xml
<CustomField>
    <fullName>OrgLimitName__c</fullName>
    <formula>OrgLimitType__r.OrgLimitName__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Org Limit Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Snapshot__c/fields/OrgLimitType__c.field-meta.xml
<CustomField>
    <fullName>OrgLimitType__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Org Limit Type</label>
    <referenceTo>OrgLimitType__c</referenceTo>
    <relationshipLabel>Snapshots</relationshipLabel>
    <relationshipName>Snapshots</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Snapshot__c/fields/Usage__c.field-meta.xml
<CustomField>
    <fullName>Usage__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Usage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Snapshot__c/recordTypes/Apex_Job_Snapshot.recordType-meta.xml
<RecordType>
    <fullName>Apex_Job_Snapshot</fullName>
    <active>true</active>
    <description>Snapshot recordType to store Apex job related logs</description>
    <label>Apex Job Snapshot</label>
</RecordType>

force-app/main/default/objects/Snapshot__c/recordTypes/Org_Limit_Snapshot.recordType-meta.xml
<RecordType>
    <fullName>Org_Limit_Snapshot</fullName>
    <active>true</active>
    <description>Snapshot recordType to store org limit related logs</description>
    <label>Org Limit Snapshot</label>
</RecordType>

force-app/main/default/classes/ClsAforceMonitor.cls
/***************************************************************************************************************************
*   Name        : ClsAforceMonitor 
*   Date        : 06 March 2023
*   Author      : Vinayak Chanekar 
*   Description : This class contains methods for Org health and limit monitoring as a part of DASHQUOTE-393

Modification Log : 
--------------------------------------------------------------------------------
* Developer               Date                  Description
* -------------------     ------------          -----------------------
* Vinayak Chanekar        06/03/2023            Added methods snapshotOrgLimits, deleteExpiredSnapshots, snapshotFailedApexJobs   
**************************************************************************************************************************/
public class ClsAforceMonitor {
    //public static Integer BUFFER_TIME_MINUTES = 5; //to be added to custom setting
    public static final Integer MONITOR_PERIOD_HOURS_FAILED_APEX = 3; //to be added to custom setting
    public static final String SNAPSHOT_RECORDTYPE_DEVNAME_APEX_JOB = 'Apex_Job_Snapshot';
    public static final String SNAPSHOT_RECORDTYPE_DEVNAME_ORG_LIMIT = 'Org_Limit_Snapshot';
    //Adding script to populate data into OrgLimitType object - to be added as post deployment step
    private static void dataSetup(){
        List<OrgLimitType__c> lstOrgLimitTypes = new List<OrgLimitType__c>(); 
        Set<String> existingOrgLimits = new Set<string>();
        for(OrgLimitType__c orgLimitType : [SELECT Id, OrgLimitName__c FROM OrgLimitType__c 
                                            LIMIT 100])
        {
            existingOrgLimits.add(orgLimitType.OrgLimitName__c);            
        }
        Map<String,System.OrgLimit> limitsMap = OrgLimits.getMap();
        for(String orgLimitName : limitsMap.keySet()){
            if(!existingOrgLimits.contains(orgLimitName)){
                OrgLimitType__c oLT = new OrgLimitType__c(OrgLimitName__c = orgLimitName);
                lstOrgLimitTypes.add(oLT);
            }
            
        }
        if(!lstOrgLimitTypes.isEmpty()){
            insert lstOrgLimitTypes;
        }
    }
    
    //Method to take Snapshot of Org Limits based on Active Org Limit Monitoring and Retreival Frequency.
    public static void snapshotOrgLimits(){
        List<Snapshot__c> lstSnapshots = new List<Snapshot__c>();
        List<OrgLimitType__c> updateOrgLimitType = new List<OrgLimitType__c>();
        Map<String,System.OrgLimit> limitsMap = OrgLimits.getMap();
        for(OrgLimitType__c orgLimitType : [SELECT Id, OrgLimitName__c, RetrievalFrequency__c, LastRetrievalDate__c FROM OrgLimitType__c 
                                            WHERE IsActive__c = true 
                                            LIMIT 100])
        {
            
            //To check if lastRetrivalData + Retrieval Frequency is less than current time with a buffer of 5 minutes.
            if(orgLimitType.LastRetrievalDate__c == null || 
               (orgLimitType.LastRetrievalDate__c != null && 
                orgLimitType.RetrievalFrequency__c != null &&
                (DateTime.Now() >= orgLimitType.LastRetrievalDate__c.addHours(Integer.valueOf(orgLimitType.RetrievalFrequency__c)))
               )
              ){
                  System.OrgLimit currentOrgLimit = limitsMap.get(orgLimitType.OrgLimitName__c);
                  Snapshot__c ss = new Snapshot__c();
                  ss.RecordTypeId = Schema.SObjectType.Snapshot__c.getRecordTypeInfosByDeveloperName().get(SNAPSHOT_RECORDTYPE_DEVNAME_ORG_LIMIT).getRecordTypeId();
                  ss.OrgLimitType__c = orgLimitType.Id;
                  ss.Usage__c = currentOrgLimit.getValue();
                  ss.MaxLimit__c = currentOrgLimit.getLimit();
                  lstSnapshots.add(ss);
                  
                  orgLimitType.LastRetrievalDate__c = System.Now();
                  updateOrgLimitType.add(orgLimitType);
              } 
        }
        if(!lstSnapshots.isEmpty()){
            insert lstSnapshots;
        }
        if(!updateOrgLimitType.isEmpty()){
            update updateOrgLimitType;
        }
    }
    
    public static void deleteExpiredSnapshots(){
        List<Snapshot__c> lstDeleteSnapshots = new List<Snapshot__c>();
        lstDeleteSnapshots = [SELECT Id from Snapshot__c WHERE IsExpired__c = true LIMIT 10000];
        if (!lstDeleteSnapshots.isEmpty()){
            Delete lstDeleteSnapshots;
        }
    }
    
    /* Method to log failed apex jobs */
    public static void snapshotFailedApexJobs(){
        List<Snapshot__c> lstFailedApexJobs = new List<Snapshot__c>();
        Datetime monitorDt = Datetime.now().addHours(-1 * MONITOR_PERIOD_HOURS_FAILED_APEX);
        for(AsyncApexJob failedJob : [SELECT id,ApexClass.Name,ExtendedStatus, Status 
                                      FROM AsyncApexJob where CreatedDate > :MonitorDt
                                      AND ExtendedStatus LIKE '%failed%'
                                      LIMIT 10000 ])
        {
            Snapshot__c ss = new Snapshot__c();
            ss.RecordTypeId = Schema.SObjectType.Snapshot__c.getRecordTypeInfosByDeveloperName().get(SNAPSHOT_RECORDTYPE_DEVNAME_APEX_JOB).getRecordTypeId();
            ss.AsyncApexJobId__c = failedJob.Id;
            ss.ApexJobName__c = failedJob.ApexClass.Name;
            ss.Description__c = failedJob.ExtendedStatus;
            lstFailedApexJobs.add(ss);
        }
        if(!lstFailedApexJobs.isEmpty()){
            insert lstFailedApexJobs;
        }
    }
}